### ISSUE TITLE
Zoom buttons

### ISSUE THREAD

**Issue by aspirisen** [ben-xD/geojsons#1]
Hi, I must say this an awesome project 👍 
It has a lot of functionality and works good as a docs/example for nebula + deck.gl + react-map-gl

I am curious do you plan to add zoom buttons? I was trying to use `NavigationControl` from `react-map-gl` and had no luck. Then I found `MapboxOverlay` in [docs](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay#using-with-react-map-gl). After that zoom control started working, but nebula functionality stoped working.

Thanks.

**Comment by uxduck** [comment]
Hey @aspirisen :)

Thanks for raising the issue

react-map-gl's `NavigationControl` is rendered below deck.gl, so I don't think it can be used - you wouldn't be able to click it. It's the same for the map attribution, so I implemented my own as I wanted the maptiler and OSM attribution to work.

Adding **custom** zoom controls would probably work, so I've done that in 11904c0ec33a68c2ca60c51eef9f5dcbd1c06643 (and added tooltips in 0fb23579904377e2c6b4a276a981e5411a11bdd0).

Try it on https://geojsons.com/

https://github.com/ben-xD/geojsons/assets/24711048/17291038-92c7-4f1e-9ca8-0d3cdce28c41

**Comment by aspirisen** [comment]
Looks awesome! Thanks.
